package com.arcadia.dao;

import com.arcadia.model.FishShip;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface FishShipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fish_ship
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fish_ship
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    int insert(FishShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fish_ship
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    int insertSelective(FishShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fish_ship
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    FishShip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fish_ship
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    int updateByPrimaryKeySelective(FishShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fish_ship
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    int updateByPrimaryKey(FishShip record);


    List<FishShip> selectListByCondtions(FishShip record);




}