package com.arcadia.model;

import java.util.Date;

public class FishShip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_ship.id
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_ship.ship_code
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private String shipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_ship.ship_type
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private String shipType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_ship.ship_period
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private String shipPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_ship.ship_amount
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private Integer shipAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_ship.create_time
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_ship.ship_level
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private String shipLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_ship.limit_period
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private Integer limitPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_ship.experience
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private Integer experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_ship.level
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_ship.status
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_ship.id
     *
     * @return the value of t_fish_ship.id
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_ship.id
     *
     * @param id the value for t_fish_ship.id
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_ship.ship_code
     *
     * @return the value of t_fish_ship.ship_code
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public String getShipCode() {
        return shipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_ship.ship_code
     *
     * @param shipCode the value for t_fish_ship.ship_code
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setShipCode(String shipCode) {
        this.shipCode = shipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_ship.ship_type
     *
     * @return the value of t_fish_ship.ship_type
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public String getShipType() {
        return shipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_ship.ship_type
     *
     * @param shipType the value for t_fish_ship.ship_type
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setShipType(String shipType) {
        this.shipType = shipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_ship.ship_period
     *
     * @return the value of t_fish_ship.ship_period
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public String getShipPeriod() {
        return shipPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_ship.ship_period
     *
     * @param shipPeriod the value for t_fish_ship.ship_period
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setShipPeriod(String shipPeriod) {
        this.shipPeriod = shipPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_ship.ship_amount
     *
     * @return the value of t_fish_ship.ship_amount
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public Integer getShipAmount() {
        return shipAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_ship.ship_amount
     *
     * @param shipAmount the value for t_fish_ship.ship_amount
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setShipAmount(Integer shipAmount) {
        this.shipAmount = shipAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_ship.create_time
     *
     * @return the value of t_fish_ship.create_time
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_ship.create_time
     *
     * @param createTime the value for t_fish_ship.create_time
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_ship.ship_level
     *
     * @return the value of t_fish_ship.ship_level
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public String getShipLevel() {
        return shipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_ship.ship_level
     *
     * @param shipLevel the value for t_fish_ship.ship_level
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setShipLevel(String shipLevel) {
        this.shipLevel = shipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_ship.limit_period
     *
     * @return the value of t_fish_ship.limit_period
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public Integer getLimitPeriod() {
        return limitPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_ship.limit_period
     *
     * @param limitPeriod the value for t_fish_ship.limit_period
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setLimitPeriod(Integer limitPeriod) {
        this.limitPeriod = limitPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_ship.experience
     *
     * @return the value of t_fish_ship.experience
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public Integer getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_ship.experience
     *
     * @param experience the value for t_fish_ship.experience
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_ship.level
     *
     * @return the value of t_fish_ship.level
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_ship.level
     *
     * @param level the value for t_fish_ship.level
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_ship.status
     *
     * @return the value of t_fish_ship.status
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_ship.status
     *
     * @param status the value for t_fish_ship.status
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }
}