package com.arcadia.model;

import java.util.Date;

public class FishSeaflight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_seaflight.id
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_seaflight.ship_code
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private String shipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_seaflight.expert_profit_min
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private Long expertProfitMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_seaflight.expert_profit_max
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private Long expertProfitMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_seaflight.create_time
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_seaflight.departure_time
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private Date departureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fish_seaflight.over_time
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    private Date overTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_seaflight.id
     *
     * @return the value of t_fish_seaflight.id
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_seaflight.id
     *
     * @param id the value for t_fish_seaflight.id
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_seaflight.ship_code
     *
     * @return the value of t_fish_seaflight.ship_code
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public String getShipCode() {
        return shipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_seaflight.ship_code
     *
     * @param shipCode the value for t_fish_seaflight.ship_code
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setShipCode(String shipCode) {
        this.shipCode = shipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_seaflight.expert_profit_min
     *
     * @return the value of t_fish_seaflight.expert_profit_min
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public Long getExpertProfitMin() {
        return expertProfitMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_seaflight.expert_profit_min
     *
     * @param expertProfitMin the value for t_fish_seaflight.expert_profit_min
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setExpertProfitMin(Long expertProfitMin) {
        this.expertProfitMin = expertProfitMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_seaflight.expert_profit_max
     *
     * @return the value of t_fish_seaflight.expert_profit_max
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public Long getExpertProfitMax() {
        return expertProfitMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_seaflight.expert_profit_max
     *
     * @param expertProfitMax the value for t_fish_seaflight.expert_profit_max
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setExpertProfitMax(Long expertProfitMax) {
        this.expertProfitMax = expertProfitMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_seaflight.create_time
     *
     * @return the value of t_fish_seaflight.create_time
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_seaflight.create_time
     *
     * @param createTime the value for t_fish_seaflight.create_time
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_seaflight.departure_time
     *
     * @return the value of t_fish_seaflight.departure_time
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public Date getDepartureTime() {
        return departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_seaflight.departure_time
     *
     * @param departureTime the value for t_fish_seaflight.departure_time
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setDepartureTime(Date departureTime) {
        this.departureTime = departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fish_seaflight.over_time
     *
     * @return the value of t_fish_seaflight.over_time
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public Date getOverTime() {
        return overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fish_seaflight.over_time
     *
     * @param overTime the value for t_fish_seaflight.over_time
     *
     * @mbggenerated Tue Nov 28 23:54:08 CST 2017
     */
    public void setOverTime(Date overTime) {
        this.overTime = overTime;
    }
}